server:
  port: 8001
  servlet:
    context-path: /MedicalSystem
  tomcat:
    max-http-header-size: 8192


spring:
  #设置文件上传的大小限制
  data:
    mongodb:
      host: 43.142.168.114
      port: 27017
      database: medical
  http:
    servlet:
      multipart:
        max-file-size: 500Mb
        max-request-size: 500Mb


